name: perl-CGI-Application-Plugin-MessageStack
upstream: http://search.cpan.org/dist/CGI-Application-Plugin-MessageStack/
description: Message stack for your CGI
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: protected
  create_from: master
type: public
