name: perl-Config-Grammar
upstream: http://search.cpan.org/dist/Config-Grammar/
description: Grammar-based, user-friendly config parser
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: protected
  create_from: master
type: public
