name: perl-MooseX-ConfigFromFile
upstream: http://search.cpan.org/dist/MooseX-ConfigFromFile/
description: Abstract Moose role for setting attributes from a configfile
branches:
- name: master
  type: protected
- name: openEuler-20.09
  type: protected
  create_from: master
type: public
