name: system-config-language
description: A graphical interface for modifying the system language
upstream: https://pagure.io/system-config-language
branches:
- name: master
  type: protected
- name: openEuler-20.03-LTS-Next
  type: protected
  create_from: master
- name: openEuler-21.09
  type: protected
  create_from: master
- name: openEuler-22.03-LTS-Next
  type: protected
  create_from: openEuler-21.09
- name: openEuler-22.03-LTS
  type: protected
  create_from: openEuler-22.03-LTS-Next
type: public
