name: Infrastructure
description: The infrastructure team is responsible for system function development and maintenance of the openEuler community.
mailing_list: infra@openeuler.org
meeting_url: https://etherpad.openeuler.org/p/infra-weekly-meeting-recaps
mature_level: startup
mentors:
- gitee_id: genedna
  name: Maquanyi
  email: genedna@gmail.com
maintainers:
- gitee_id: georgecao
  name: George.Cao
  organization: Huawei
  email: caozhi1214@qq.com
- gitee_id: TommyLike
  name: TommyLike
  email: tommylikehu@gmail.com
committers:
- gitee_id: dogsheng
  name: Jingqicuipibinggan
  email: 960055655@qq.com
- gitee_id: miao_kaibo
  name: MiaoKaibo
  email: miaokaibo@outlook.com
- gitee_id: freesky-edward
  name: freesky-edward
  email: freesky.edward@gmail.com
- gitee_id: imjoey
  name: imjoey
  email: majunjie@apache.org
- gitee_id: zerodefect
  name: Fred_Li
  email: yongle.li@gmail.com
- gitee_id: zhuchunyi
  name: Trainey
  email: zhuchunyi@huawei.com
- gitee_id: zhongjun2
  name: zhongjun2
  email: 526521735@qq.com
- gitee_id: zhengyuhanghans
  name: Zhengyuhang
  email: zhengyuhang@huawei.com
- gitee_id: zyp-rock
  name: zyp
  email: zhuyanpeng@huawei.com
- gitee_id: xiangxinyong
  name: xiangxinyong
  email: xiangxingyong@qq.com  
repositories:
- repo: openeuler/infrastructure
- repo: openeuler/blog
- repo: openeuler/website
- repo: openeuler/go-gitee
- repo: openeuler/gitbook-theme-hugo
- repo: openeuler/tool-collections
- repo: openeuler/cve-manager
- repo: openeuler/website-v2
  additional_contributors:
  - gitee_id: morningwyt
    name: wyt
    orgnization: Huawei
    email: morningwyt@163.com
  - gitee_id: suisuisuisuixin
    name: Gaohechao
    email: 1159963696@qq.com
  - gitee_id: zou_jinda
    name: Zoujinda
    email: 826835384@qq.com
  - gitee_id: ligenghong
    name: Ligenghong
    email: 296331906@qq.com
  - gitee_id: zhang_xiaopan
    name: Zhangxiaopan
    email: 273478353@qq.com
  - gitee_id: lesliexx
    name: Lixinxing
    email: 969966273@qq.com
  - gitee_id: chenyujiahw
    name: chenyujia1021
    email: chenyujia3@huawei.com
  - gitee_id: xzx666
    name: Xiaozhixin
    email: 563905150@qq.com
