name: rqt_reconfigure
description: This rqt plugin succeeds former dynamic_reconfigure's GUI (reconfigure_gui),
  and provides the way to view and edit the parameters that are accessible via dynamic_reconfigure.
upstream: https://github.com/ros-visualization/rqt_reconfigure
branches:
- name: master
  type: protected
type: public
