name: python-django-configurations
description: A helper for organizing Django settings.
upstream: https://github.com/jazzband/django-configurations
branches:
- name: master
  type: protected
type: public
