name: cinnamon-settings-daemon
description: The settings daemon for the Cinnamon desktop.
upstream: https://github.com/linuxmint/cinnamon-settings-daemon
branches:
- name: master
  type: protected
type: public

