name: python-ConfigSpace
description: Creation and manipulation of parameter configuration spaces
upstream: https://github.com/automl/ConfigSpace
branches:
- name: master
  type: protected
type: publicname:python-ConfigSpace
