name: kf5-knotifyconfig
description: kf5-knotifyconfig is configuration dialog for desktop notifications
upstream: https://github.com/KDE/knotifyconfig
branches:
- name: master
  type: protected
type: public